### ISSUE TITLE
Configuration Jenkins - Gitlab

### ISSUE THREAD

**Issue by zepouet** [Treeptik/docker-training-ci#1]
Comment envisagez vous la configuration d'un outil vis à vis de l'autre ?
Documentez vous ceci ? 
Automatisation via des scripts ou bien on utilise les volumes docker ?

Nicolas

**Comment by punkstarman** [comment]
Je préconise d'utiliser des variables d'environnement.

**Comment by zepouet** [comment]
En fait vous avez utilisé un trigger pour poller sur Jenkins. Ceci vous évite d'utiliser le plugin Jenkins dans Gitlab.

Cela va bien même s'il faut attendre une minute max pour déclencher le build.
